# Generated by Django 6.0.2 on 2026-09-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner'), ('dessert', 'Dessert')], max_length=20)),
                ('ingredients', models.TextField(blank=True)),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('jain', models.BooleanField(default=False)),
                ('high_protein', models.BooleanField(default=False)),
                ('low_oil', models.BooleanField(default=False)),
                ('spice_level', models.PositiveSmallIntegerField(default=0)),
                ('sweetness_level', models.PositiveSmallIntegerField(default=0)),
                ('preparation_time', models.PositiveIntegerField(help_text='Preparation time in minutes.')),
                ('available', models.BooleanField(default=True)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags.')),
                ('suitable_moods', models.TextField(blank=True, help_text='Comma-separated moods this item suits.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
