# Generated by Django 6.0.2 on 2026-09-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional food photograph used in the menu.', null=True, upload_to='food/'),
        ),
    ]
