from django.core.management.base import BaseCommand

from menu.models import FoodItem


MENU_ITEMS = [
    {'name': 'Veg Noodles', 'slug': 'veg-noodles', 'description': 'Wok-tossed noodles with fresh vegetables.', 'price': '80.00', 'category': 'Chinese', 'meal_type': 'lunch', 'ingredients': 'Noodles, cabbage, carrot, capsicum, soy sauce', 'vegetarian': True, 'vegan': True, 'jain': False, 'high_protein': False, 'low_oil': False, 'spice_level': 2, 'sweetness_level': 0, 'preparation_time': 12, 'available': True, 'tags': 'quick, chinese, filling', 'suitable_moods': 'hungry, craving'},
    {'name': 'Paneer Roll', 'slug': 'paneer-roll', 'description': 'Spiced paneer and vegetables wrapped in a soft roti.', 'price': '70.00', 'category': 'Rolls', 'meal_type': 'snack', 'ingredients': 'Paneer, roti, onion, capsicum, spices', 'vegetarian': True, 'vegan': False, 'jain': False, 'high_protein': True, 'low_oil': False, 'spice_level': 2, 'sweetness_level': 0, 'preparation_time': 10, 'available': True, 'tags': 'paneer, protein, quick', 'suitable_moods': 'hungry, energetic'},
    {'name': 'Veg Sandwich', 'slug': 'veg-sandwich', 'description': 'Grilled sandwich with vegetables and chutney.', 'price': '50.00', 'category': 'Sandwiches', 'meal_type': 'snack', 'ingredients': 'Bread, potato, cucumber, tomato, mint chutney', 'vegetarian': True, 'vegan': False, 'jain': False, 'high_protein': False, 'low_oil': True, 'spice_level': 1, 'sweetness_level': 0, 'preparation_time': 8, 'available': True, 'tags': 'light, grilled, quick', 'suitable_moods': 'light, studying'},
    {'name': 'Samosa', 'slug': 'samosa', 'description': 'Crisp pastry filled with spicy potato and peas.', 'price': '20.00', 'category': 'Snacks', 'meal_type': 'snack', 'ingredients': 'Flour, potato, peas, spices', 'vegetarian': True, 'vegan': True, 'jain': False, 'high_protein': False, 'low_oil': False, 'spice_level': 2, 'sweetness_level': 0, 'preparation_time': 3, 'available': True, 'tags': 'fried, classic, budget', 'suitable_moods': 'snacking, craving'},
    {'name': 'Masala Dosa', 'slug': 'masala-dosa', 'description': 'Crisp rice-lentil crepe with potato masala and chutney.', 'price': '70.00', 'category': 'South Indian', 'meal_type': 'breakfast', 'ingredients': 'Rice, lentils, potato, curry leaves, spices', 'vegetarian': True, 'vegan': True, 'jain': False, 'high_protein': False, 'low_oil': True, 'spice_level': 2, 'sweetness_level': 0, 'preparation_time': 15, 'available': True, 'tags': 'south indian, breakfast, crispy', 'suitable_moods': 'hungry, comfort'},
    {'name': 'Idli Sambar', 'slug': 'idli-sambar', 'description': 'Steamed idlis served with lentil sambar.', 'price': '50.00', 'category': 'South Indian', 'meal_type': 'breakfast', 'ingredients': 'Rice, urad dal, lentils, vegetables, spices', 'vegetarian': True, 'vegan': True, 'jain': False, 'high_protein': True, 'low_oil': True, 'spice_level': 1, 'sweetness_level': 0, 'preparation_time': 8, 'available': True, 'tags': 'south indian, healthy, breakfast', 'suitable_moods': 'fresh, light'},
    {'name': 'Veg Fried Rice', 'slug': 'veg-fried-rice', 'description': 'Seasoned rice stir-fried with mixed vegetables.', 'price': '80.00', 'category': 'Chinese', 'meal_type': 'lunch', 'ingredients': 'Rice, carrot, beans, cabbage, soy sauce', 'vegetarian': True, 'vegan': True, 'jain': False, 'high_protein': False, 'low_oil': False, 'spice_level': 2, 'sweetness_level': 0, 'preparation_time': 10, 'available': True, 'tags': 'chinese, rice, filling', 'suitable_moods': 'hungry, comfort'},
    {'name': 'Paneer Rice Bowl', 'slug': 'paneer-rice-bowl', 'description': 'Paneer curry with rice and seasonal vegetables.', 'price': '110.00', 'category': 'Bowls', 'meal_type': 'lunch', 'ingredients': 'Paneer, rice, vegetables, tomato gravy, spices', 'vegetarian': True, 'vegan': False, 'jain': False, 'high_protein': True, 'low_oil': True, 'spice_level': 2, 'sweetness_level': 0, 'preparation_time': 12, 'available': True, 'tags': 'paneer, protein, meal', 'suitable_moods': 'hungry, energetic'},
    {'name': 'Aloo Paratha', 'slug': 'aloo-paratha', 'description': 'Whole-wheat flatbread stuffed with spiced potato.', 'price': '60.00', 'category': 'North Indian', 'meal_type': 'breakfast', 'ingredients': 'Wheat flour, potato, spices, butter', 'vegetarian': True, 'vegan': False, 'jain': False, 'high_protein': False, 'low_oil': False, 'spice_level': 2, 'sweetness_level': 0, 'preparation_time': 12, 'available': True, 'tags': 'north indian, breakfast, filling', 'suitable_moods': 'hungry, comfort'},
    {'name': 'Chole Bhature', 'slug': 'chole-bhature', 'description': 'Spiced chickpea curry with fluffy fried bread.', 'price': '90.00', 'category': 'North Indian', 'meal_type': 'lunch', 'ingredients': 'Chickpeas, flour, tomato, onion, spices', 'vegetarian': True, 'vegan': True, 'jain': False, 'high_protein': True, 'low_oil': False, 'spice_level': 3, 'sweetness_level': 0, 'preparation_time': 15, 'available': True, 'tags': 'north indian, hearty, spicy', 'suitable_moods': 'very hungry, celebratory'},
    {'name': 'Veg Burger', 'slug': 'veg-burger', 'description': 'Vegetable patty burger with lettuce and sauces.', 'price': '70.00', 'category': 'Fast Food', 'meal_type': 'snack', 'ingredients': 'Burger bun, vegetable patty, lettuce, tomato, sauces', 'vegetarian': True, 'vegan': False, 'jain': False, 'high_protein': False, 'low_oil': False, 'spice_level': 1, 'sweetness_level': 0, 'preparation_time': 8, 'available': True, 'tags': 'fast food, burger, quick', 'suitable_moods': 'craving, fun'},
    {'name': 'French Fries', 'slug': 'french-fries', 'description': 'Golden potato fries with seasoning.', 'price': '50.00', 'category': 'Fast Food', 'meal_type': 'snack', 'ingredients': 'Potato, oil, salt, seasoning', 'vegetarian': True, 'vegan': True, 'jain': False, 'high_protein': False, 'low_oil': False, 'spice_level': 1, 'sweetness_level': 0, 'preparation_time': 7, 'available': True, 'tags': 'fried, snack, fast food', 'suitable_moods': 'snacking, fun'},
    {'name': 'Poha', 'slug': 'poha', 'description': 'Light flattened rice with peanuts and vegetables.', 'price': '40.00', 'category': 'Breakfast', 'meal_type': 'breakfast', 'ingredients': 'Flattened rice, potato, peanuts, curry leaves, lemon', 'vegetarian': True, 'vegan': True, 'jain': False, 'high_protein': False, 'low_oil': True, 'spice_level': 1, 'sweetness_level': 0, 'preparation_time': 6, 'available': True, 'tags': 'breakfast, light, budget', 'suitable_moods': 'fresh, light'},
    {'name': 'Upma', 'slug': 'upma', 'description': 'Savory semolina breakfast with vegetables.', 'price': '40.00', 'category': 'Breakfast', 'meal_type': 'breakfast', 'ingredients': 'Semolina, vegetables, curry leaves, mustard seeds', 'vegetarian': True, 'vegan': True, 'jain': False, 'high_protein': False, 'low_oil': True, 'spice_level': 1, 'sweetness_level': 0, 'preparation_time': 7, 'available': True, 'tags': 'breakfast, light, south indian', 'suitable_moods': 'fresh, studying'},
    {'name': 'Maggi', 'slug': 'maggi', 'description': 'Instant noodles cooked with masala.', 'price': '45.00', 'category': 'Noodles', 'meal_type': 'snack', 'ingredients': 'Instant noodles, masala, vegetables', 'vegetarian': True, 'vegan': False, 'jain': False, 'high_protein': False, 'low_oil': False, 'spice_level': 2, 'sweetness_level': 0, 'preparation_time': 6, 'available': True, 'tags': 'quick, noodles, budget', 'suitable_moods': 'late night, studying'},
    {'name': 'Paneer Maggi', 'slug': 'paneer-maggi', 'description': 'Masala noodles topped with paneer cubes.', 'price': '70.00', 'category': 'Noodles', 'meal_type': 'snack', 'ingredients': 'Instant noodles, paneer, masala, vegetables', 'vegetarian': True, 'vegan': False, 'jain': False, 'high_protein': True, 'low_oil': False, 'spice_level': 2, 'sweetness_level': 0, 'preparation_time': 8, 'available': True, 'tags': 'noodles, paneer, quick', 'suitable_moods': 'late night, hungry'},
    {'name': 'Lemon Juice', 'slug': 'lemon-juice', 'description': 'Chilled lemon drink with a touch of salt.', 'price': '25.00', 'category': 'Beverages', 'meal_type': 'snack', 'ingredients': 'Lemon, water, sugar, salt', 'vegetarian': True, 'vegan': True, 'jain': True, 'high_protein': False, 'low_oil': True, 'spice_level': 0, 'sweetness_level': 2, 'preparation_time': 3, 'available': True, 'tags': 'drink, refreshing, summer', 'suitable_moods': 'tired, refreshed'},
    {'name': 'Mango Lassi', 'slug': 'mango-lassi', 'description': 'Sweet chilled yogurt drink with mango.', 'price': '50.00', 'category': 'Beverages', 'meal_type': 'dessert', 'ingredients': 'Yogurt, mango pulp, sugar, cardamom', 'vegetarian': True, 'vegan': False, 'jain': True, 'high_protein': True, 'low_oil': True, 'spice_level': 0, 'sweetness_level': 4, 'preparation_time': 4, 'available': True, 'tags': 'drink, sweet, cooling', 'suitable_moods': 'happy, refreshed'},
    {'name': 'Tea', 'slug': 'tea', 'description': 'Hot Indian milk tea with aromatic spices.', 'price': '15.00', 'category': 'Beverages', 'meal_type': 'snack', 'ingredients': 'Tea leaves, milk, sugar, ginger', 'vegetarian': True, 'vegan': False, 'jain': True, 'high_protein': False, 'low_oil': True, 'spice_level': 0, 'sweetness_level': 2, 'preparation_time': 4, 'available': True, 'tags': 'hot drink, chai, budget', 'suitable_moods': 'tired, studying'},
    {'name': 'Coffee', 'slug': 'coffee', 'description': 'Hot milk coffee for a quick energy boost.', 'price': '25.00', 'category': 'Beverages', 'meal_type': 'snack', 'ingredients': 'Coffee, milk, sugar', 'vegetarian': True, 'vegan': False, 'jain': True, 'high_protein': False, 'low_oil': True, 'spice_level': 0, 'sweetness_level': 2, 'preparation_time': 4, 'available': True, 'tags': 'hot drink, caffeine, study', 'suitable_moods': 'tired, focused'},
    {'name': 'Veg Biryani', 'slug': 'veg-biryani', 'description': 'Fragrant basmati rice layered with vegetables and warm spices.', 'price': '95.00', 'category': 'Rice Bowls', 'meal_type': 'lunch', 'ingredients': 'Basmati rice, vegetables, yogurt, spices', 'vegetarian': True, 'vegan': False, 'jain': False, 'high_protein': False, 'low_oil': False, 'spice_level': 3, 'sweetness_level': 0, 'preparation_time': 14, 'available': True, 'tags': 'rice, spicy, filling', 'suitable_moods': 'hungry, happy'},
    {'name': 'Veg Thali', 'slug': 'veg-thali', 'description': 'A balanced plate of dal, seasonal sabzi, rice and rotis.', 'price': '120.00', 'category': 'North Indian', 'meal_type': 'lunch', 'ingredients': 'Dal, vegetables, rice, wheat flour', 'vegetarian': True, 'vegan': True, 'jain': False, 'high_protein': True, 'low_oil': True, 'spice_level': 2, 'sweetness_level': 0, 'preparation_time': 12, 'available': True, 'tags': 'healthy, complete meal, filling', 'suitable_moods': 'hungry, energetic'},
    {'name': 'Cold Coffee', 'slug': 'cold-coffee', 'description': 'Creamy chilled coffee blended for an afternoon reset.', 'price': '55.00', 'category': 'Beverages', 'meal_type': 'snack', 'ingredients': 'Coffee, milk, ice, sugar', 'vegetarian': True, 'vegan': False, 'jain': True, 'high_protein': False, 'low_oil': True, 'spice_level': 0, 'sweetness_level': 3, 'preparation_time': 5, 'available': True, 'tags': 'cold, coffee, refreshing', 'suitable_moods': 'tired, happy'},
    {'name': 'Gulab Jamun', 'slug': 'gulab-jamun', 'description': 'Two warm milk-solid dumplings soaked in cardamom syrup.', 'price': '35.00', 'category': 'Desserts', 'meal_type': 'dessert', 'ingredients': 'Milk solids, flour, sugar, cardamom', 'vegetarian': True, 'vegan': False, 'jain': True, 'high_protein': False, 'low_oil': False, 'spice_level': 0, 'sweetness_level': 5, 'preparation_time': 2, 'available': True, 'tags': 'dessert, sweet, classic', 'suitable_moods': 'happy, celebration'},
    {'name': 'Vanilla Ice Cream', 'slug': 'vanilla-ice-cream', 'description': 'A cool vanilla scoop for a sweet break between classes.', 'price': '40.00', 'category': 'Desserts', 'meal_type': 'dessert', 'ingredients': 'Milk, cream, sugar, vanilla', 'vegetarian': True, 'vegan': False, 'jain': True, 'high_protein': False, 'low_oil': False, 'spice_level': 0, 'sweetness_level': 4, 'preparation_time': 1, 'available': True, 'tags': 'dessert, sweet, cooling', 'suitable_moods': 'happy, tired'},
    {'name': 'Sprouts Chaat', 'slug': 'sprouts-chaat', 'description': 'Tangy mixed sprouts with cucumber, tomato and lemon.', 'price': '55.00', 'category': 'Healthy Bites', 'meal_type': 'snack', 'ingredients': 'Mixed sprouts, cucumber, tomato, lemon', 'vegetarian': True, 'vegan': True, 'jain': False, 'high_protein': True, 'low_oil': True, 'spice_level': 1, 'sweetness_level': 0, 'preparation_time': 5, 'available': True, 'tags': 'healthy, protein, light', 'suitable_moods': 'energetic, light'},
    {'name': 'Jain Veg Wrap', 'slug': 'jain-veg-wrap', 'description': 'Fresh vegetables and paneer wrapped without onion or garlic.', 'price': '75.00', 'category': 'Rolls', 'meal_type': 'snack', 'ingredients': 'Roti, paneer, capsicum, cabbage, spices', 'vegetarian': True, 'vegan': False, 'jain': True, 'high_protein': True, 'low_oil': True, 'spice_level': 1, 'sweetness_level': 0, 'preparation_time': 9, 'available': True, 'tags': 'jain, protein, quick', 'suitable_moods': 'hungry, energetic'},
    {'name': 'Cheese Corn Toast', 'slug': 'cheese-corn-toast', 'description': 'Toasted bread with sweet corn, cheese and herbs.', 'price': '60.00', 'category': 'Sandwiches', 'meal_type': 'snack', 'ingredients': 'Bread, corn, cheese, herbs', 'vegetarian': True, 'vegan': False, 'jain': True, 'high_protein': False, 'low_oil': False, 'spice_level': 1, 'sweetness_level': 1, 'preparation_time': 7, 'available': False, 'tags': 'crispy, cheese, snack', 'suitable_moods': 'craving, happy'},
]


class Command(BaseCommand):
    help = 'Create or update sample college canteen menu items.'

    def handle(self, *args, **options):
        created_count = 0
        updated_count = 0

        for item in MENU_ITEMS:
            slug = item['slug']
            _, created = FoodItem.objects.update_or_create(slug=slug, defaults=item)
            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Menu seeded: {created_count} created, {updated_count} updated.'
            )
        )
